# Generated by Django 5.0.6 on 2024-06-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
